export const SET_LANGUAGE = "SET_LANGUAGE";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_VALIDATE_SUCCESS = "AUTH_VALIDATE_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_BUFFER = "AUTH_BUFFER";
export const AUTH_BUFFER_FAIL = "AUTH_BUFFER_FAIL";

export const MODAL_CONFIRM_OPEN = "MODAL_CONFIRM_OPEN";
export const MODAL_CONFIRM_CLOSE = "MODAL_CONFIRM_CLOSE";
